server:
  shutdown: graceful
spring:
  application:
    name: gout-backend


  threads:
    virtual:
      enabled: true

  mvc:
    problemdetails:
      enabled: true

  # Database connection - PostgreSQL
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/gout}
    username: ${DATABASE_USER:goutapp}
    password: ${DATABASE_PASSWORD:secret}

  # Database Migration
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    validate-on-migrate: ${FLYWAY_VALIDATE_ON_MIGRATE:true}
    locations: classpath:db/migration



management:
  endpoints:
    web:
      exposure:
        include: "health,info,metric,prometheus"
